spring:
  config:
    location: classpath:service.properties
  profiles:
    active: dev
  datasource:
      url: jdbc:mysql://127.0.0.1:3306/weather?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&allowMultiQueries=true
      username: root
      password: Waiting911216
      driverClassName: com.mysql.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource

      initialSize: 2
      minIdle: 3
      maxActive: 50
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 3600000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,slf4j
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      useGlobalDataSourceStat: true
      removeAbandoned: true
      removeAbandonedTimeout: 80
      logAbandoned: true

server:
  port: 8085


