CREATE DATABASE IF NOT EXISTS joysuch_chemical CHARACTER SET UTF8;
use joysuch_chemical;

DROP TABLE IF EXISTS SYS_USER;
-- 系统用户表
CREATE TABLE `SYS_USER` (
  `UUID` varchar(36) NOT NULL DEFAULT '',
  `PARENT` varchar(64) DEFAULT NULL,
  `USER_NAME` varchar(64) DEFAULT NULL,
  `PASSWORD` varchar(64) DEFAULT NULL,
  `LICENCE` varchar(128) DEFAULT NULL,
  `SECRET` varchar(128) DEFAULT NULL,
  `USER_TYPE` int(11) DEFAULT NULL COMMENT '用户类型，根据不同的类型，给予不同的权限',
  `REMARK` varchar(512) DEFAULT NULL,
   USER_PERMISSION_JSON TEXT DEFAULT NULL,
   EMPLOYEE_IDS TEXT DEFAULT NULL,
  `CREATE_TIME` datetime DEFAULT NULL,
  `CREATE_BY` varchar(64) DEFAULT NULL,
  `UPDATE_TIME` datetime DEFAULT NULL,
  `UPDATE_BY` varchar(64) DEFAULT NULL,
  `VALID` tinyint(1) DEFAULT '1' COMMENT '有效性，物理删除',
  PRIMARY KEY (`UUID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS `SYS_CONFIG`;
CREATE TABLE `SYS_CONFIG` (
  `UUID` varchar(36) NOT NULL DEFAULT '',
  `USER_ID` varchar(128) DEFAULT NULL,
  `BUILD_ID` varchar(64) DEFAULT NULL,
  `CONFIG_CODE` varchar(128) DEFAULT NULL,
  `CONFIG_NAME` varchar(256) DEFAULT NULL,
  `CONFIG_VAL` varchar(512) DEFAULT NULL,
  `CONFIG_TYPE` varchar(32) DEFAULT NULL,
  `CAN_EDIT` tinyint(1) DEFAULT '1',
  PRIMARY KEY (`UUID`),
  KEY `IDX_SYS_CONFIG_USER_ID` (`USER_ID`),
  KEY `IDX_SYS_CONFIG_BUILD_ID` (`BUILD_ID`),
  KEY `IDX_SYS_CONFIG_CONFIG_CODE` (`CONFIG_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS SYS_USER_BUILDING_REL;
-- 子级用户与查看权限的关联关系表
CREATE TABLE `SYS_USER_BUILDING_REL` (
  `UUID` varchar(36) NOT NULL DEFAULT '',
  USER_ID VARCHAR(36) DEFAULT NULL,
  USER_NAME VARCHAR(128) DEFAULT NULL,
  USER_PERMISSION_JSON TEXT DEFAULT NULL,
  `CREATE_TIME` datetime DEFAULT NULL,
  `CREATE_BY` varchar(64) DEFAULT NULL,
  `UPDATE_TIME` datetime DEFAULT NULL,
  `UPDATE_BY` varchar(64) DEFAULT NULL,
  PRIMARY KEY (`UUID`),
   KEY `IDX_SYS_USER_BUILDING_REL_USER_ID` (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS APPLICATION_BUILDING_INFO;
-- 应用层的建筑信息表
CREATE TABLE `APPLICATION_BUILDING_INFO` (
 `UUID` varchar(36) NOT NULL DEFAULT '',
  USER_ID VARCHAR(36) DEFAULT NULL,
  BUILDING_ID VARCHAR(36) DEFAULT NULL,
  BUILDING_NAME VARCHAR(128) DEFAULT NULL,
  `BUILDING_FMAP_ID` varchar(36) DEFAULT NULL,
  `FMAP_WEB_KEY` varchar(64) DEFAULT NULL,
  `FMAP_WEB_NAME` varchar(64) DEFAULT NULL,
  `FMAP_IOS_KEY` varchar(64) DEFAULT NULL,
  `FMAP_ANDROID_KEY` varchar(64) DEFAULT NULL,
 PRIMARY KEY (`UUID`),
  KEY `IDX_APPLICATION_BUILDING_INFO_USER_ID` (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS SYS_LOG_INFO;
-- 系统操作日志表
CREATE TABLE `SYS_LOG_INFO` (
  `UUID` varchar(36) NOT NULL DEFAULT '',
  `CLASS_NAME` varchar(36) DEFAULT NULL,
  `METHOD_NAME` varchar(36) DEFAULT NULL,
  `URI` varchar(64) DEFAULT NULL,
  `CODE` varchar(64) DEFAULT NULL,
  `OP_MODULE` varchar(16) DEFAULT NULL,
  `REQ_IP` varchar(32) DEFAULT NULL,
  `URL` varchar(2048) DEFAULT NULL,
  `REQ_REFER` varchar(128) DEFAULT NULL,
  `REQ_HOST` varchar(64) DEFAULT NULL,
  `OP_TYPE` varchar(16) DEFAULT NULL,
  `USERNAME` varchar(36) DEFAULT NULL,
  `ERROR_MSG` varchar(2048) DEFAULT NULL,
  `PARAM_JSON` varchar(4096) DEFAULT NULL,
  `OP_TIME` datetime DEFAULT NULL,
  PRIMARY KEY (`UUID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS LOCATION_LABEL;
-- 标签表
CREATE TABLE `LOCATION_LABEL` (
  `UUID` varchar(36) NOT NULL DEFAULT '',
  `BUILD_ID` varchar(64) DEFAULT NULL,
  `SN` varchar(36) DEFAULT NULL,
  `REMARK` varchar(256) DEFAULT NULL,
  `BATTERY` int(11) DEFAULT '0',
  `WORK_STATUS` int(11) DEFAULT '0',
  `ONLINE` tinyint(1) DEFAULT '0' ,
  `BINDED` int(11) DEFAULT '0',
  `BIND_NAME` varchar(64) DEFAULT NULL,
  `BINDER_ID` varchar(36) DEFAULT NULL,
  `CREATE_TIME` datetime DEFAULT NULL,
  `CREATE_BY` varchar(64) DEFAULT NULL,
  `UPDATE_TIME` datetime DEFAULT NULL,
  `UPDATE_BY` varchar(64) DEFAULT NULL,
  PRIMARY KEY (`UUID`),
  KEY `IDX_LOCATION_LABEL_CREATE_BY` (`CREATE_BY`),
  KEY `IDX_LOCATION_LABEL_WORK_STATUS` (`WORK_STATUS`),
  KEY `IDX_LOCATION_LABEL_BUILD_ID` (`BUILD_ID`),
  KEY `IDX_LOCATION_LABEL_SN` (`SN`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS AREA;
-- 区域表
CREATE TABLE `AREA` (
  `UUID` varchar(36) NOT NULL DEFAULT '',
  `USER_ID` varchar(64) DEFAULT NULL,
  `BUILD_ID` varchar(64) DEFAULT NULL,
  `AREA_NAME` varchar(256) DEFAULT NULL,
  `AREA_LEVEL` int(11) DEFAULT '1',
  `PARENT_ID` varchar(36) DEFAULT NULL,
  `CREATE_TIME` datetime DEFAULT NULL,
  `CREATE_BY` varchar(64) DEFAULT NULL,
  `UPDATE_TIME` datetime DEFAULT NULL,
  `UPDATE_BY` varchar(64) DEFAULT NULL,
  PRIMARY KEY (`UUID`),
  KEY `IDX_AREA_PARENT_ID` (`PARENT_ID`),
  KEY `IDX_AREA_AREA_LEVEL` (`AREA_LEVEL`),
  KEY `IDX_AREA_USER_ID` (`USER_ID`),
  KEY `IDX_AREA_BUILD_ID` (`BUILD_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS AREA_RAIL_REL;
-- 区域围栏关联表
CREATE TABLE `AREA_RAIL_REL` (
  `UUID` varchar(36) NOT NULL DEFAULT '',
  `AREA_ID` varchar(64) DEFAULT NULL,
  `AREA_NAME` varchar(128) DEFAULT NULL,
  `RAIL_ID` varchar(64) DEFAULT NULL,
  `RAIL_NAME` varchar(128) DEFAULT NULL,
  PRIMARY KEY (`UUID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS ALARM_AREA;
-- 区域报警围栏表
CREATE TABLE `ALARM_AREA` (
  `UUID` varchar(36) NOT NULL DEFAULT '',
  `RAIL_ID` varchar(64) DEFAULT NULL,
  `RAIL_NAME` varchar(256) DEFAULT NULL,
  `USER_ID` varchar(36) DEFAULT NULL,
  `BUILD_ID` varchar(36) DEFAULT NULL,
  `FLOOR_NO` varchar(36) DEFAULT NULL,
  `REMARK` varchar(512) DEFAULT NULL,
  `OVER_BOUNDARY_ALARM` int(11) DEFAULT NULL,
  `STOP_ALARM` int(11) DEFAULT NULL,
  `STOP_LIMIT_SECONDS` int(11) DEFAULT NULL,
  `CREATE_TIME` datetime DEFAULT NULL,
  `CREATE_BY` varchar(64) DEFAULT NULL,
  `UPDATE_TIME` datetime DEFAULT NULL,
  `UPDATE_BY` varchar(64) DEFAULT NULL,
  `ACTIVE_PERIOD` varchar(1024) DEFAULT NULL,
  PRIMARY KEY (`UUID`),
   KEY `IDX_ALARM_AREA_RAIL_ID` (`RAIL_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS RAIL_POINT;
-- 围栏点位表
CREATE TABLE `RAIL_POINT` (
  `UUID` varchar(36) NOT NULL DEFAULT '',
  `RAIL_ID` varchar(36) DEFAULT NULL,
  `X` int(11) DEFAULT NULL,
  `Y` int(11) DEFAULT NULL,
  PRIMARY KEY (`UUID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS EMPLOYEE_TYPE;
-- 人员类型表
CREATE TABLE `EMPLOYEE_TYPE` (
  `UUID` varchar(36) NOT NULL DEFAULT '',
  `BUILD_ID` varchar(36) DEFAULT NULL,
  `TYPE_NAME` varchar(256) DEFAULT NULL,
  `FIELDS_JSON` TEXT  DEFAULT NULL,
  PRIMARY KEY (`UUID`),
   KEY `IDX_EMPLOYEE_TYPE_BUILD_ID` (`BUILD_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS PRIV_TEMPLATE;
-- 围栏报警模板表
CREATE TABLE `PRIV_TEMPLATE` (
  `UUID` varchar(36) NOT NULL DEFAULT '',
  `BUILD_ID` varchar(64) DEFAULT NULL,
  `NAME` varchar(64) DEFAULT NULL,
  `EMPLOYEE_TYPE` varchar(64) DEFAULT NULL,
  `PRIV_INFO` mediumtext,
  PRIMARY KEY (`UUID`),
   KEY `IDX_PRIV_TEMPLATE_BUILD_ID` (`BUILD_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



DROP TABLE IF EXISTS EMPLOYEE;
-- 工作人员表
CREATE TABLE `EMPLOYEE` (
  `UUID` varchar(36) NOT NULL DEFAULT '',
  `USER_ID` varchar(64) DEFAULT NULL,
  `BUILD_ID` varchar(64) DEFAULT NULL,
  `NAME` varchar(256) DEFAULT NULL,
  `SN` varchar(36) DEFAULT NULL COMMENT 'MAC地址',
  `EMPLOYEE_TYPE_ID` varchar(36) DEFAULT NULL,
  `EMPLOYEE_TYPE_NAME` varchar(64) DEFAULT NULL,
  `AREA_ID` varchar(64) DEFAULT NULL,
  `AREA_NAME` varchar(64) DEFAULT NULL,
  `FIELDS_INFO` mediumtext,
  `PRIV_INFO` mediumtext,
  `CREATE_TIME` datetime DEFAULT NULL,
  `CREATE_BY` varchar(64) DEFAULT NULL,
  `UPDATE_TIME` datetime DEFAULT NULL,
  `UPDATE_BY` varchar(64) DEFAULT NULL,
  `HEAD_PIC` varchar(256) DEFAULT NULL,
  `ICON_PIC` varchar(256) DEFAULT NULL,
  PRIMARY KEY (`UUID`),
  KEY `IDX_EMPLOYEE_USER_ID` (`USER_ID`),
  KEY `IDX_EMPLOYEE_BUILD_ID` (`BUILD_ID`),
  KEY `IDX_EMPLOYEE_AREA_ID` (`AREA_ID`),
  KEY `IDX_EMPLOYEE_SN` (`SN`),
  KEY `IDX_EMPLOYEE_TYPE` (`EMPLOYEE_TYPE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS ALARM_BELL;
-- 警铃表
CREATE TABLE `ALARM_BELL` (
  `UUID` varchar(36) NOT NULL DEFAULT '',
  `NAME` varchar(256) DEFAULT NULL,
  `SN` varchar(64) DEFAULT NULL,
  `USER_ID` varchar(64) DEFAULT NULL,
  `BUILD_ID` varchar(64) DEFAULT NULL,
  `FLOOR_NO` varchar(36) DEFAULT NULL,
  `X` int(11) DEFAULT NULL,
  `Y` int(11) DEFAULT NULL,
  `RANGE_TYPE` varchar(64) DEFAULT NULL,
  `RANGE_FLOOR_NOS` varchar(256) DEFAULT NULL,
  `REMARK` varchar(512) DEFAULT NULL,
  `CREATE_TIME` datetime DEFAULT NULL,
  `CREATE_BY` varchar(64) DEFAULT NULL,
  `UPDATE_TIME` datetime DEFAULT NULL,
  `UPDATE_BY` varchar(64) DEFAULT NULL,
  PRIMARY KEY (`UUID`),
    KEY `IDX_ALARM_BELL_BUILD_ID` (`BUILD_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS ALARM_BELL_RAIL_REL;
-- 警铃围栏关联表
CREATE TABLE `ALARM_BELL_RAIL_REL` (
  `UUID` varchar(36) NOT NULL DEFAULT '',
  `BELL_ID` varchar(64) DEFAULT NULL,
  `BELL_NAME` varchar(64) DEFAULT NULL,
  `RAIL_ID` varchar(64) DEFAULT NULL,
  `RAIL_NAME` varchar(36) DEFAULT NULL,
  PRIMARY KEY (`UUID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS ALARM_BELL_CTRL_EVENT;
-- 警铃控制事件表
CREATE TABLE `ALARM_BELL_CTRL_EVENT` (
  `UUID` varchar(36) NOT NULL DEFAULT '',
  `BELL_ID` varchar(64) DEFAULT NULL,
  `BELL_NAME` varchar(64) DEFAULT NULL,
  `BELL_SN` varchar(64) DEFAULT NULL,
  `EVENT_ID` varchar(64) DEFAULT NULL,
  `EVENT_TYPE` varchar(64) DEFAULT NULL,
  `EVENT_MAC` varchar(64) DEFAULT NULL,
  `EVENT_NAME` varchar(128) DEFAULT NULL,
  `OPER_TYPE` varchar(32) DEFAULT NULL COMMENT '开on 关off',
  `OPER_RES` int(11) DEFAULT NULL,
  `RES_TIME` datetime DEFAULT NULL,
  `CREATE_TIME` datetime DEFAULT NULL,
  `CREATE_BY` varchar(64) DEFAULT NULL,
  `UPDATE_TIME` datetime DEFAULT NULL,
  `UPDATE_BY` varchar(64) DEFAULT NULL,
  PRIMARY KEY (`UUID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS MONITOR;
-- 监控摄像头表
CREATE TABLE `MONITOR` (
  `UUID` varchar(36) NOT NULL DEFAULT '',
  `NAME` varchar(64) DEFAULT NULL,
  `SN` varchar(64) DEFAULT NULL,
  `USER_ID` varchar(64) DEFAULT NULL,
  `BUILD_ID` varchar(64) DEFAULT NULL,
  `FLOOR_NO` varchar(36) DEFAULT NULL,
  `X` int(11) DEFAULT NULL,
  `Y` int(11) DEFAULT NULL,
  `TRANS_HOST` varchar(64) DEFAULT NULL,
  `TRANS_NAME` varchar(64) DEFAULT NULL,
  `TRANS_PASS` varchar(64) DEFAULT NULL,
  `TRANS_PORT` int(11) DEFAULT NULL,
  `REMARK` varchar(512) DEFAULT NULL,
  `CREATE_TIME` datetime DEFAULT NULL,
  `CREATE_BY` varchar(64) DEFAULT NULL,
  `UPDATE_TIME` datetime DEFAULT NULL,
  `UPDATE_BY` varchar(64) DEFAULT NULL,
  `SERVER_PORT` int(11) DEFAULT NULL,
  `REAL_RTSP_URL` varchar(128) DEFAULT NULL,
  `HISTORY_RTSP_URL` varchar(128) DEFAULT NULL,
  `RTSP_TIME_FORMAT` varchar(32) DEFAULT NULL,
  `RTSP_DATE_FORMAT` varchar(32) DEFAULT NULL,
  PRIMARY KEY (`UUID`),
 KEY `IDX_MONITOR_BUILD_ID` (`BUILD_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS MONITOR_RAIL_REL;
-- 摄像头围栏关联表
CREATE TABLE `MONITOR_RAIL_REL` (
  `UUID` varchar(36) NOT NULL DEFAULT '',
  `MONITOR_ID` varchar(64) DEFAULT NULL,
  `MONITOR_NAME` varchar(64) DEFAULT NULL,
  `RAIL_ID` varchar(64) DEFAULT NULL,
  `RAIL_NAME` varchar(36) DEFAULT NULL,
  PRIMARY KEY (`UUID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS ICON_PICTURE;
-- 人员图标表
CREATE TABLE `ICON_PICTURE` (
  `UUID` varchar(36) NOT NULL DEFAULT '',
  `BUILD_ID` varchar(64) DEFAULT NULL,
  `USER_ID` varchar(64) DEFAULT NULL,
  `ICON_NAME` varchar(512) DEFAULT NULL,
  `ICON_PATH` varchar(512) DEFAULT NULL,
   `CREATE_TIME` datetime DEFAULT NULL,
  `CREATE_BY` varchar(64) DEFAULT NULL,
  `UPDATE_TIME` datetime DEFAULT NULL,
  `UPDATE_BY` varchar(64) DEFAULT NULL,
  PRIMARY KEY (`UUID`),
  KEY `IDX_ICON_PICTURE_BUILD_ID` (`BUILD_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO ICON_PICTURE
(UUID, BUILD_ID, USER_ID, ICON_NAME, ICON_PATH, CREATE_TIME, CREATE_BY, UPDATE_TIME, UPDATE_BY)
VALUES
('1', null, null, 'default_1', '$$home$$seekcy$$chemical-data$$iconPicture$$default_1.png', now(), '', now(), ''),
('2', null, null, 'default_2', '$$home$$seekcy$$chemical-data$$iconPicture$$default_2.png', now(), '', now(), ''),
('3', null, null, 'default_3', '$$home$$seekcy$$chemical-data$$iconPicture$$default_3.png', now(), '', now(), ''),
('4', null, null, 'default_4', '$$home$$seekcy$$chemical-data$$iconPicture$$default_4.png', now(), '', now(), '');

DROP TABLE IF EXISTS ALARM_EVENT;
-- 报警事件表
CREATE TABLE `ALARM_EVENT` (
  `UUID` varchar(36) NOT NULL DEFAULT '',
  `BUILD_ID` varchar(64) DEFAULT NULL,
  `AREA_NAME` varchar(512) DEFAULT NULL,
  `TYPE` varchar(64) DEFAULT NULL,
  `BINDER_ID` varchar(36) DEFAULT NULL,
  `MAC` varchar(64) DEFAULT NULL,
  `NAME` varchar(128) DEFAULT NULL,
  `TIME` datetime DEFAULT NULL,
  `LOCATION_FLOOR_NO` varchar(32) DEFAULT NULL,
  `LOCATION_X` int(11) DEFAULT NULL,
  `LOCATION_Y` int(11) DEFAULT NULL,
  `DETAIL` mediumtext,
  `REMARK` varchar(256) DEFAULT NULL,
  `MONITORS` mediumtext,
  `ALARM_BELLS` mediumtext,
  `HANDLE_TIME` datetime DEFAULT NULL,
  `HANDLE_REMARK` varchar(512) DEFAULT NULL,
  `CREATE_TIME` datetime DEFAULT NULL,
  `CREATE_BY` varchar(64) DEFAULT NULL,
  `UPDATE_TIME` datetime DEFAULT NULL,
  `UPDATE_BY` varchar(64) DEFAULT NULL,
  PRIMARY KEY (`UUID`),
  KEY `IDX_ALARM_EVENT_TYPE` (`TYPE`),
  KEY `IDX_ALARM_EVENT_BINDER_ID` (`BINDER_ID`),
  KEY `IDX_ALARM_EVENT_MAC` (`MAC`),
  KEY `IDX_ALARM_EVENT_NAME` (`NAME`),
  KEY `IDX_ALARM_EVENT_TIME` (`TIME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS ALARM_AREA_LOG;
-- 围栏日志表
CREATE TABLE `ALARM_AREA_LOG` (
  `UUID` varchar(36) NOT NULL DEFAULT '',
  `RAIL_ID` varchar(64) DEFAULT NULL,
  `RAIL_NAME` varchar(64) DEFAULT NULL,
  `NAME` varchar(64) DEFAULT NULL,
  `SN` varchar(64) DEFAULT NULL,
  `TYPE` int(11) DEFAULT NULL,
  `EVENT_TIME` bigint(20) DEFAULT NULL,
  `HAS_PERM` int(11) DEFAULT NULL,
  `CREATE_TIME` datetime DEFAULT NULL,
  `CREATE_BY` varchar(64) DEFAULT NULL,
  `UPDATE_TIME` datetime DEFAULT NULL,
  `UPDATE_BY` varchar(64) DEFAULT NULL,
  PRIMARY KEY (`UUID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS HD_RECORDER;
-- 硬盘录像机表
CREATE TABLE `HD_RECORDER` (
  `UUID` varchar(36) NOT NULL DEFAULT '',
  `BUILD_ID` varchar(64) DEFAULT NULL,
  `NAME` varchar(64) DEFAULT NULL,
  `TRANS_HOST` varchar(64) DEFAULT NULL,
  `TRANS_NAME` varchar(64) DEFAULT NULL,
  `TRANS_PASS` varchar(64) DEFAULT NULL,
  `TRANS_PORT` int(11) DEFAULT NULL,
  `REMARK` varchar(256) DEFAULT NULL,
  `MONITOR_STRING` varchar(4096) DEFAULT NULL,
  PRIMARY KEY (`UUID`),
  KEY `HD_RECORDER_BUILD_ID` (`BUILD_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS SYSTEM_LOGGER;
-- 系统日志表
CREATE TABLE `SYSTEM_LOGGER` (
  `UUID` varchar(36) NOT NULL DEFAULT '',
  `BUILD_ID` varchar(64) DEFAULT NULL,
  `USER_NAME` varchar(64) DEFAULT NULL,
  `OPERATION` varchar(64) DEFAULT NULL,
  `MODULE_NAME` varchar(64) DEFAULT NULL,
  `LANGUAGE_ZH_CN` varchar(2048) DEFAULT NULL,
  `LANGUAGE_EN_US` varchar(2048) DEFAULT NULL,
  `LANGUAGE_JA_JP` varchar(2048) DEFAULT NULL,
  `OP_VARIATE_NAME` varchar(4096) DEFAULT NULL,
  `CREATE_TIME` datetime DEFAULT NULL,
  `CREATE_BY` varchar(64) DEFAULT NULL,
  PRIMARY KEY (`UUID`),
  KEY `SYSTEM_LOGGER_BUILD_ID` (`BUILD_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS SCREEN_PREVIEW;
-- 屏幕数据展示预览表
CREATE TABLE `SCREEN_PREVIEW` (
  `UUID` varchar(36) NOT NULL DEFAULT '',
  `BUILD_ID` varchar(64) DEFAULT NULL,
  `NAME` varchar(64) DEFAULT NULL,
  `TYPE` varchar(64) DEFAULT NULL,
  `INDEX` INT(2) DEFAULT NULL,
  `SHOW_TOTAL_PERSON_COUNT` tinyint(1) DEFAULT 0,
  `SHOW_WAY_PERSON_COUNT` tinyint(1) DEFAULT 0,
  `AREA_IDS` TEXT DEFAULT NULL,
  `AREA_JSON` TEXT DEFAULT NULL,
  `CREATE_TIME` datetime DEFAULT NULL,
  `CREATE_BY` varchar(64) DEFAULT NULL,
  `UPDATE_TIME` datetime DEFAULT NULL,
  `UPDATE_BY` varchar(64) DEFAULT NULL,
  PRIMARY KEY (`UUID`),
  KEY `SCREEN_PREVIEW_BUILD_ID` (`BUILD_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS AREA_SAFE;
-- 区域安全表
CREATE TABLE `AREA_SAFE` (
  `UUID` varchar(64) NOT NULL,
  `BUILD_ID` varchar(64) NOT NULL,
  `AREA_SAFE_NAME` varchar(64) NOT NULL,
  `AREA_SAFE_TYPE` varchar(64) NOT NULL,
  `AREA_IDS` TEXT DEFAULT NULL,
  `RAIL_IDS` TEXT DEFAULT NULL,

  CHECK_OVER tinyint(1) DEFAULT 0,
  OVER_NUM int(11) DEFAULT NULL,
  OVER_TIME int(11) DEFAULT NULL,
  OVER_STATUS tinyint(1) DEFAULT 1,
  CHECK_LACK tinyint(1) DEFAULT 0,
  LACK_NUM int(11) DEFAULT NULL,
  LACK_TIME int(11) DEFAULT NULL,
  LACK_STATUS tinyint(1) DEFAULT 1,
  CHECK_STILL tinyint(1) DEFAULT 0,
  STILL_TIME int(11) DEFAULT NULL,
  CHECK_STAY tinyint(1) DEFAULT 0,
  STAY_TIME int(11) DEFAULT NULL,
  CHECK_OVER_BOUNDARY tinyint(1) DEFAULT 0,
  CHECK_OVER_BOUNDARY_INTO tinyint(1) DEFAULT 0,
  CHECK_OVER_BOUNDARY_OUT tinyint(1) DEFAULT 0,
  CHECK_ONE_KEY_ALARM tinyint(1) DEFAULT 0,

  ACTIVE_PERIOD varchar(1024) DEFAULT NULL,

  `CREATE_TIME` datetime DEFAULT NULL,
  `CREATE_BY` varchar(64) DEFAULT NULL,
  `UPDATE_TIME` datetime DEFAULT NULL,
  `UPDATE_BY` varchar(64) DEFAULT NULL,
  PRIMARY KEY (`UUID`),
  KEY `AREA_SAFE_BUILD_ID` (`BUILD_ID`),
  KEY `AREA_SAFE_AREA_SAFE_TYPE` (`AREA_SAFE_TYPE`),
  KEY `AREA_SAFE_AREA_SAFE_NAME` (`AREA_SAFE_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


