#========化工厂2.1================================================================

DROP TABLE IF EXISTS PATROL_POINT;
-- 巡检点表
CREATE TABLE `PATROL_POINT` (
  `UUID` varchar(36) NOT NULL DEFAULT '',
  `BUILD_ID` varchar(64) DEFAULT NULL,
  `NAME` varchar(512) DEFAULT NULL,
  `TYPE` varchar(64) DEFAULT NULL,
  `REMARK` varchar(4096) DEFAULT NULL,
  `CREATE_TIME` datetime DEFAULT NULL,
  `CREATE_BY` varchar(64) DEFAULT NULL,
  `UPDATE_TIME` datetime DEFAULT NULL,
  `UPDATE_BY` varchar(64) DEFAULT NULL,
  PRIMARY KEY (`UUID`),
  KEY `PATROL_POINT_BUILD_ID` (`BUILD_ID`),
  KEY `PATROL_POINT_TYPE` (`TYPE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS PATROL_POINT_RAIL_REL;
-- 巡检点与围栏关联表
CREATE TABLE `PATROL_POINT_RAIL_REL` (
  `UUID` varchar(36) NOT NULL DEFAULT '',
  `BUILD_ID` varchar(64) DEFAULT NULL,
  `PATROL_POINT_ID` varchar(64) DEFAULT NULL,
  `PATROL_POINT_NAME` varchar(512) DEFAULT NULL,
  `RAIL_ID` varchar(64) DEFAULT NULL,
  `RAIL_NAME` varchar(64) DEFAULT NULL,
  PRIMARY KEY (`UUID`),
  KEY `PATROL_POINT_RAIL_REL_BUILD_ID` (`BUILD_ID`),
  KEY `PATROL_POINT_RAIL_REL_PATROL_POINT_ID` (`PATROL_POINT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS PATROL_POINT_BEACON_REL;
-- 巡检点与beacon关联表
CREATE TABLE `PATROL_POINT_BEACON_REL` (
  `UUID` varchar(36) NOT NULL DEFAULT '',
  `BUILD_ID` varchar(64) DEFAULT NULL,
  `PATROL_POINT_ID` varchar(64) DEFAULT NULL,
  `PATROL_POINT_NAME` varchar(512) DEFAULT NULL,
  `DEVICE_UUID` varchar(64) DEFAULT NULL,
  `MAJOR` INT(11) DEFAULT NULL,
  `MINOR` INT(11) DEFAULT NULL,
  `RSSI_LIMIT` INT(11) DEFAULT NULL,
  PRIMARY KEY (`UUID`),
  KEY `PATROL_POINT_BEACON_REL_BUILD_ID` (`BUILD_ID`),
  KEY `PATROL_POINT_BEACON_REL_PATROL_POINT_ID` (`PATROL_POINT_ID`),
  KEY `PATROL_POINT_BEACON_REL_DEVICE_UUID` (`DEVICE_UUID`),
  KEY `PATROL_POINT_BEACON_REL_MAJOR` (`MAJOR`),
  KEY `PATROL_POINT_BEACON_REL_MINOR` (`MINOR`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS IBEACON;
-- IBEACON
CREATE TABLE `IBEACON` (
  `UUID` varchar(64) NOT NULL,
  `BUILD_ID` varchar(64) NOT NULL,
  `MAC` varchar(128) DEFAULT NULL,
  `DEVICE_ID` varchar(128) DEFAULT NULL,
  `DEVICE_UUID` varchar(256) DEFAULT NULL,
  `DEVICE_TYPE` varchar(10) DEFAULT NULL,
  `MAJOR` int(5) DEFAULT NULL,
  `MINOR` int(5) DEFAULT NULL,
  `FLOOR_NO` varchar(36) DEFAULT NULL,
  `X` int(10) DEFAULT NULL,
  `Y` int(10) DEFAULT NULL,
  PRIMARY KEY (`UUID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS PATROL_AREA;
-- 巡检区域表
CREATE TABLE `PATROL_AREA` (
  `UUID` varchar(64) NOT NULL,
  `BUILD_ID` varchar(64) NOT NULL,
  `NAME` varchar(512) DEFAULT NULL,
  `RAIL_ID` varchar(64) DEFAULT NULL,
  `RAIL_NAME` varchar(512) DEFAULT NULL,
  `CHECK_LEAST_NUM` tinyint(1) DEFAULT 0,
  `LEAST_NUM_LIMIT` int(5) DEFAULT NULL,
  `CHECK_STAY_TIME` tinyint(1) DEFAULT 0,
  `STAY_TIME_LIMIT` int(5) DEFAULT NULL,
  `REMARK` varchar(4096) DEFAULT NULL,
  `CREATE_TIME` datetime DEFAULT NULL,
  `CREATE_BY` varchar(64) DEFAULT NULL,
  `UPDATE_TIME` datetime DEFAULT NULL,
  `UPDATE_BY` varchar(64) DEFAULT NULL,
  PRIMARY KEY (`UUID`),
  KEY `PATROL_AREA_BUILD_ID` (`BUILD_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS PATROL_AREA_POINT_REL;
-- 巡检区域与巡检点关联表
CREATE TABLE `PATROL_AREA_POINT_REL` (
  `UUID` varchar(64) NOT NULL,
  `BUILD_ID` varchar(64) NOT NULL,
  `PATROL_AREA_ID` varchar(64) DEFAULT NULL,
  `PATROL_AREA_NAME` varchar(512) DEFAULT NULL,
  `MUST_PATROL` tinyint(1) DEFAULT 0,
  `PATROL_POINT_ID` varchar(64) DEFAULT NULL,
  `PATROL_POINT_NAME` varchar(512) DEFAULT NULL,
  PRIMARY KEY (`UUID`),
  KEY `PATROL_AREA_POINT_REL_BUILD_ID` (`BUILD_ID`),
  KEY `PATROL_AREA_POINT_REL_PATROL_PATROL_AREA_ID` (`PATROL_AREA_ID`),
  KEY `PATROL_AREA_POINT_REL_PATROL_PATROL_POINT_ID` (`PATROL_POINT_ID`),
  KEY `PATROL_AREA_POINT_REL_PATROL_PATROL_MUST_PATROL` (`MUST_PATROL`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS PATROL_PATH;
-- 巡检路线表
CREATE TABLE `PATROL_PATH` (
  `UUID` varchar(64) NOT NULL,
  `BUILD_ID` varchar(64) NOT NULL,
  `NAME` varchar(512) DEFAULT NULL,
  `PATROL_WEEK` varchar(64) DEFAULT NULL,
  `BEFORE_TIME` int(5) DEFAULT NULL,
  `AFTER_TIME` int(5) DEFAULT NULL,
  `REMARK` varchar(4096) DEFAULT NULL,
  `CREATE_TIME` datetime DEFAULT NULL,
  `CREATE_BY` varchar(64) DEFAULT NULL,
  `UPDATE_TIME` datetime DEFAULT NULL,
  `UPDATE_BY` varchar(64) DEFAULT NULL,
  PRIMARY KEY (`UUID`),
  KEY `PATROL_PATH_BUILD_ID` (`BUILD_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS PATROL_GROUP;
-- 巡检路班组表
CREATE TABLE `PATROL_GROUP` (
  `UUID` varchar(64) NOT NULL,
  `BUILD_ID` varchar(64) NOT NULL,
  `NAME` varchar(512) DEFAULT NULL,
  `REMARK` varchar(4096) DEFAULT NULL,
  `EMPLOYEE_NAMES` varchar(4096) DEFAULT NULL,
  `CREATE_TIME` datetime DEFAULT NULL,
  `CREATE_BY` varchar(64) DEFAULT NULL,
  `UPDATE_TIME` datetime DEFAULT NULL,
  `UPDATE_BY` varchar(64) DEFAULT NULL,
  PRIMARY KEY (`UUID`),
  KEY `PATROL_PATH_BUILD_ID` (`BUILD_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS PATROL_GROUP_EMPLOYEE_REL;
-- 巡检班组与人员关联表
CREATE TABLE `PATROL_GROUP_EMPLOYEE_REL` (
  `UUID` varchar(64) NOT NULL,
  `BUILD_ID` varchar(64) NOT NULL,
  `PATROL_GROUP_ID` varchar(64) NOT NULL,
  `PATROL_GROUP_NAME` varchar(512) DEFAULT NULL,
  `EMPLOYEE_ID` varchar(64) NOT NULL,
  `EMPLOYEE_NAME` varchar(512) DEFAULT NULL,
  PRIMARY KEY (`UUID`),
  KEY `PATROL_GROUP_EMPLOYEE_REL_BUILD_ID` (`BUILD_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS PATROL_PATH_GROUP_REL;
-- 巡检路线与巡检班组关联表
CREATE TABLE `PATROL_PATH_GROUP_REL` (
  `UUID` varchar(64) NOT NULL,
  `BUILD_ID` varchar(64) NOT NULL,
  `PATROL_PATH_ID` varchar(64) NOT NULL,
  `PATROL_PATH_NAME` varchar(512) DEFAULT NULL,
  `PATROL_GROUP_ID` varchar(64) NOT NULL,
  `PATROL_GROUP_NAME` varchar(512) DEFAULT NULL,
  PRIMARY KEY (`UUID`),
  KEY `PATROL_PATH_GROUP_REL_BUILD_ID` (`BUILD_ID`),
  KEY `PATROL_PATH_GROUP_REL_PATROL_PATH_ID` (`PATROL_PATH_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS PATROL_PATH_AREA_REL;
-- 巡检区域与巡检路线关联表
CREATE TABLE `PATROL_PATH_AREA_REL` (
  `UUID` varchar(64) NOT NULL,
  `BUILD_ID` varchar(64) NOT NULL,
  `PATROL_PATH_ID` varchar(64) NOT NULL,
  `PATROL_PATH_NAME` varchar(512) DEFAULT NULL,
  `PATROL_AREA_ID` varchar(64) NOT NULL,
  `PATROL_AREA_NAME` varchar(512) DEFAULT NULL,
  `PATROL_AREA_INDEX` int(5) DEFAULT NULL,
  PRIMARY KEY (`UUID`),
  KEY `PATROL_PATH_AREA_REL_BUILD_ID` (`BUILD_ID`),
  KEY `PATROL_PATH_AREA_REL_PATROL_PATH_ID` (`PATROL_PATH_ID`),
  KEY `PATROL_PATH_AREA_REL_PATROL_AREA_ID` (`PATROL_AREA_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS PATROL_PATH_TIME_REL;
-- 巡检路线与巡检时间关联表
CREATE TABLE `PATROL_PATH_TIME_REL` (
  `UUID` varchar(64) NOT NULL,
  `BUILD_ID` varchar(64) NOT NULL,
  `PATROL_TIME` varchar(64) NOT NULL,
  `ACTIVE_TIME` varchar(64) NOT NULL,
  `ACTIVE_WEEK` varchar(64) NOT NULL,
  `PATROL_PATH_ID` varchar(64) NOT NULL,
  `PATROL_PATH_NAME` varchar(512) DEFAULT NULL,
  PRIMARY KEY (`UUID`),
  KEY `PATROL_PATH_TIME_REL_BUILD_ID` (`BUILD_ID`),
  KEY `PATROL_PATH_TIME_REL_PATROL_PATH_ID` (`PATROL_PATH_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



DROP TABLE IF EXISTS PATROL_EVENT_BASE_DATA;
-- 巡检事件基础数据表
CREATE TABLE `PATROL_EVENT_BASE_DATA` (
  `UUID` varchar(64) NOT NULL,
  `BUILD_ID` varchar(64) NOT NULL,
  `AREA_NAME` varchar(512) DEFAULT NULL,
  `SN` varchar(64) DEFAULT NULL,
  EMPLOYEE_ID varchar(64) DEFAULT NULL,
  EMPLOYEE_NAME varchar(512) DEFAULT NULL,
  RAIL_ID varchar(64) DEFAULT NULL,
  RAIL_NAME varchar(512) DEFAULT NULL,
  RAIL_TYPE INT(11) DEFAULT NULL,
  X INT(11) DEFAULT NULL,
  Y INT(11) DEFAULT NULL,
  DEVICE_UUID varchar(512) DEFAULT NULL,
  MAJOR INT(11) DEFAULT NULL,
  MINOR INT(11) DEFAULT NULL,
  EVENT_TYPE varchar(64) DEFAULT NULL,
  PATROL_POINT_ID varchar(64) DEFAULT NULL,
  PATROL_POINT_NAME varchar(512) DEFAULT NULL,
  PATROL_AREA_ID varchar(64) DEFAULT NULL,
  PATROL_AREA_NAME varchar(512) DEFAULT NULL,
  PATROL_PATH_ID varchar(64) DEFAULT NULL,
  PATROL_PATH_NAME varchar(512) DEFAULT NULL,
  PATROL_GROUP_ID varchar(64) DEFAULT NULL,
  PATROL_GROUP_NAME varchar(512) DEFAULT NULL,
  PATROL_TIME varchar(64) DEFAULT NULL,
  PATROL_DATE varchar(64) DEFAULT NULL,
  PATROL_EVENT_DATE datetime DEFAULT NULL,

  PRIMARY KEY (`UUID`),
  KEY `PATROL_EVENT_BASE_DATA_BUILD_ID` (`BUILD_ID`),
  KEY `PATROL_EVENT_BASE_DATA_PATROL_PATH_ID` (`PATROL_PATH_ID`),
  KEY `PATROL_EVENT_BASE_DATA_PATROL_DATE` (`PATROL_DATE`),
  KEY `PATROL_EVENT_BASE_DATA_PATROL_TIME` (`PATROL_TIME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS PATROL_PATH_DATA_CENTER;
-- 一次巡检结束，巡检路线数据表
CREATE TABLE `PATROL_PATH_DATA_CENTER` (
  `UUID` varchar(64) NOT NULL,
  `BUILD_ID` varchar(64) NOT NULL,
  PATROL_PATH_ID varchar(64) DEFAULT NULL,
  PATROL_PATH_NAME varchar(512) DEFAULT NULL,
  PATROL_PATH_STATUS tinyint(1) DEFAULT 1,
  PATROL_TIME varchar(64) DEFAULT NULL,
  PATROL_DATE varchar(64) DEFAULT NULL,
  PATROL_EVENT_DATE datetime DEFAULT NULL,

  PRIMARY KEY (`UUID`),
  KEY `PATROL_PATH_DATA_CENTER_BUILD_ID` (`BUILD_ID`),
  KEY `PATROL_PATH_DATA_CENTER_PATROL_PATH_ID` (`PATROL_PATH_ID`),
  KEY `PATROL_PATH_DATA_CENTER_PATROL_PATH_STATUS` (`PATROL_PATH_STATUS`),
  KEY `PATROL_PATH_DATA_CENTER_PATROL_DATE` (`PATROL_DATE`),
  KEY `PATROL_PATH_DATA_CENTER_PATROL_TIME` (`PATROL_TIME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS PATROL_AREA_DATA_CENTER;
-- 一次巡检结束，巡检区域数据表
CREATE TABLE `PATROL_AREA_DATA_CENTER` (
  `UUID` varchar(64) NOT NULL,
  `BUILD_ID` varchar(64) NOT NULL,
  PATROL_AREA_ID varchar(64) DEFAULT NULL,
  PATROL_AREA_NAME varchar(512) DEFAULT NULL,
  PATROL_AREA_STATUS tinyint(1) DEFAULT 1,
  PATROL_TIME varchar(64) DEFAULT NULL,
  PATROL_TIME_LENGTH INT(11) DEFAULT 0,
  PATROL_DATE varchar(64) DEFAULT NULL,
  PATROL_EVENT_DATE datetime DEFAULT NULL,
  PATROL_PATH_DATA_CENTER_ID VARCHAR(64) DEFAULT NULL,
  PRIMARY KEY (`UUID`),
  KEY `PATROL_AREA_DATA_CENTER_BUILD_ID` (`BUILD_ID`),
  KEY `PATROL_AREA_DATA_CENTER_PATROL_AREA_ID` (`PATROL_AREA_ID`),
  KEY `PATROL_AREA_DATA_CENTER_PATROL_AREA_STATUS` (`PATROL_AREA_STATUS`),
  KEY `PATROL_AREA_DATA_CENTER_PATROL_DATE` (`PATROL_DATE`),
  KEY `PATROL_AREA_DATA_CENTER_PATROL_TIME` (`PATROL_TIME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS PATROL_POINT_DATA_CENTER;
-- 一次巡检结束，巡检点位数据表
CREATE TABLE `PATROL_POINT_DATA_CENTER` (
  `UUID` varchar(64) NOT NULL,
  `BUILD_ID` varchar(64) NOT NULL,
  PATROL_POINT_ID varchar(64) DEFAULT NULL,
  PATROL_POINT_NAME varchar(512) DEFAULT NULL,
  EMPLOYEE_ID varchar(64) DEFAULT NULL,
  EMPLOYEE_NAME varchar(512) DEFAULT NULL,
  GROUP_ID varchar(64) DEFAULT NULL,
  GROUP_NAME varchar(512) DEFAULT NULL,
  SN varchar(64) DEFAULT NULL,
  PATROL_TIME varchar(64) DEFAULT NULL,
  PATROL_TIME_LENGTH INT(11) DEFAULT 0,
  PATROL_DATE varchar(64) DEFAULT NULL,
  PATROL_EVENT_DATE datetime DEFAULT NULL,
  PATROL_AREA_DATA_CENTER_ID VARCHAR(64) DEFAULT NULL,

  POINT_TYPE varchar(64) DEFAULT NULL,
  RAIL_ID varchar(64) DEFAULT NULL,
  RAIL_NAME varchar(512) DEFAULT NULL,
  DEVICE_UUID varchar(64) DEFAULT NULL,
  MAJOR INT(11) DEFAULT NULL,
  MINOR INT(11) DEFAULT NULL,

  PRIMARY KEY (`UUID`),
  KEY `PATROL_POINT_DATA_CENTER_BUILD_ID` (`BUILD_ID`),
  KEY `PATROL_POINT_DATA_CENTER_PATROL_POINT_ID` (`PATROL_POINT_ID`),
  KEY `PATROL_POINT_DATA_CENTER_PATROL_DATE` (`PATROL_DATE`),
  KEY `PATROL_POINT_DATA_CENTER_PATROL_TIME` (`PATROL_TIME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS PATROL_EMPLOYEE_DATA_BASE;
-- 以人为纬度存储巡检数据表
CREATE TABLE `PATROL_EMPLOYEE_DATA_BASE` (

  `UUID` varchar(64) NOT NULL,
  `BUILD_ID` varchar(64) NOT NULL,
  PATROL_PATH_ID varchar(64) DEFAULT NULL,
  PATROL_PATH_NAME varchar(512) DEFAULT NULL,
  EMPLOYEE_ID varchar(64) DEFAULT NULL,
  EMPLOYEE_NAME varchar(512) DEFAULT NULL,
  GROUP_ID varchar(64) DEFAULT NULL,
  GROUP_NAME varchar(512) DEFAULT NULL,
  SN varchar(64) DEFAULT NULL,
  PATROL_SUCCESS_AREA_IDS varchar(4096) DEFAULT NULL,
  PATROL_FAIL_AREA_IDS varchar(4096) DEFAULT NULL,
  PATROL_TIME_LENGTH INT(11) DEFAULT 0,
  PATROL_STATUS tinyint(1) DEFAULT 1,
  PATROL_TIME varchar(64) DEFAULT NULL,
  PATROL_DATE varchar(64) DEFAULT NULL,
  CREATE_TIME datetime DEFAULT NULL,
  PRIMARY KEY (`UUID`),
  KEY `PATROL_EMPLOYEE_DATA_BASE_BUILD_ID` (`BUILD_ID`),
  KEY `PATROL_EMPLOYEE_DATA_BASE_PATROL_STATUS` (`PATROL_STATUS`),
  KEY `PATROL_EMPLOYEE_DATA_BASE_PATROL_DATE` (`PATROL_DATE`),
  KEY `PATROL_EMPLOYEE_DATA_BASE_PATROL_TIME` (`PATROL_TIME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS PATROL_PATH_DATA_DISPLAY;
-- 巡检路线展示数据表 Patrol_Path_Data_Display类
CREATE TABLE `PATROL_PATH_DATA_DISPLAY` (

  `UUID` varchar(64) NOT NULL,
  `BUILD_ID` varchar(64) NOT NULL,
  PATROL_PATH_ID varchar(64) DEFAULT NULL,
  PATROL_PATH_NAME varchar(512) DEFAULT NULL,
  PATROL_GROUP_IDS varchar(4096) DEFAULT NULL,
  PATROL_STATUS tinyint(1) DEFAULT 1,
  PATROL_TIME varchar(64) DEFAULT NULL,
  PATROL_DATE varchar(64) DEFAULT NULL,
  PATROL_BEFORE_TIME INT(11) DEFAULT 0,
  PATROL_AFTER_TIME INT(11) DEFAULT 0,
  CREATE_TIME datetime DEFAULT NULL,

  PRIMARY KEY (`UUID`),
  KEY `PATROL_PATH_DATA_DISPLAY_BUILD_ID` (`BUILD_ID`),
  KEY `PATROL_PATH_DATA_DISPLAY_PATROL_STATUS` (`PATROL_STATUS`),
  KEY `PATROL_PATH_DATA_DISPLAY_PATROL_DATE` (`PATROL_DATE`),
  KEY `PATROL_PATH_DATA_DISPLAY_PATROL_TIME` (`PATROL_TIME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS PATH_AREA_REL_DATA_DISPLAY;
-- 巡检路线与区域展示数据关联表 Path_Area_Rel_Data_Display类
CREATE TABLE `PATH_AREA_REL_DATA_DISPLAY` (

  `UUID` varchar(64) NOT NULL,
  `BUILD_ID` varchar(64) NOT NULL,
  PATROL_AREA_ID varchar(64) DEFAULT NULL,
  PATROL_AREA_NAME varchar(512) DEFAULT NULL,
  LEAST_NUM INT(11) DEFAULT 0,
  LEAST_TIME INT(11) DEFAULT 0,
  MUST_PATROL_POINT_IDS varchar(4096) DEFAULT NULL,

  ACTUAL_NUM INT(11) DEFAULT 0,
  ACTUAL_TIME INT(11) DEFAULT 0,
  ACTUAL_MUST_PATROL_POINT_IDS varchar(4096) DEFAULT NULL,
  PATROL_PATH_DATA_DISPLAY_ID varchar(64) DEFAULT NULL,

  PRIMARY KEY (`UUID`),
  KEY `REL_PATROL_PATH_DATA_DISPLAY_ID` (`PATROL_PATH_DATA_DISPLAY_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS PATH_EMPLOYEE_REL_DATA_DISPLAY;
-- 巡检路线与人员展示数据关联表 PATH_EMPLOYEE_REL_DATA_DISPLAY类
CREATE TABLE `PATH_EMPLOYEE_REL_DATA_DISPLAY` (

  `UUID` varchar(64) NOT NULL,
  `BUILD_ID` varchar(64) NOT NULL,
  PATROL_EMPLOYEE_ID varchar(64) DEFAULT NULL,
  PATROL_EMPLOYEE_NAME varchar(512) DEFAULT NULL,
  PATROL_GROUP_ID varchar(64) DEFAULT NULL,
  PATROL_GROUP_NAME varchar(512) DEFAULT NULL,

  PATROL_PATH_DATA_DISPLAY_ID varchar(64) DEFAULT NULL,

  PRIMARY KEY (`UUID`),
  KEY `PATH_EMPLOYEE_REL_PATH_DATA_ID` (`PATROL_PATH_DATA_DISPLAY_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS PATROL_AREA_DATA_DISPLAY;
-- 巡检区域展示数据表 PATROL_AREA_DATA_DISPLAY类
CREATE TABLE `PATROL_AREA_DATA_DISPLAY` (
  `UUID` varchar(64) NOT NULL,
  `BUILD_ID` varchar(64) NOT NULL,
  PATROL_AREA_ID varchar(64) DEFAULT NULL,
  PATROL_AREA_NAME varchar(512) DEFAULT NULL,
  PATROL_STATUS tinyint(1) DEFAULT 1,
  PATROL_TIME varchar(64) DEFAULT NULL,
  PATROL_DATE varchar(64) DEFAULT NULL,
  LEAST_NUM INT(11) DEFAULT 0,
  LEAST_TIME INT(11) DEFAULT 0,
  MUST_PATROL_POINT_IDS varchar(4096) DEFAULT NULL,
  ACTUAL_NUM INT(11) DEFAULT 0,
  ACTUAL_TIME INT(11) DEFAULT 0,
  ACTUAL_MUST_PATROL_POINT_IDS varchar(4096) DEFAULT NULL,
  PATROL_PATH_ID varchar(64) DEFAULT NULL,
  PATROL_PATH_NAME varchar(512) DEFAULT NULL,
  CREATE_TIME datetime DEFAULT NULL,
  PRIMARY KEY (`UUID`),
  KEY `PATROL_AREA_DATA_DISPLAY_BUILD_ID` (`BUILD_ID`),
  KEY `PATROL_AREA_DATA_DISPLAY_PATROL_STATUS` (`PATROL_STATUS`),
  KEY `PATROL_AREA_DATA_DISPLAY_PATROL_DATE` (`PATROL_DATE`),
  KEY `PATROL_AREA_DATA_DISPLAY_PATROL_TIME` (`PATROL_TIME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



DROP TABLE IF EXISTS AREA_EMPLOYEE_REL_DATA_DISPLAY;
-- 巡检区域与人员展示数据关联表 AREA_EMPLOYEE_REL_DATA_DISPLAY类
CREATE TABLE `AREA_EMPLOYEE_REL_DATA_DISPLAY` (
  `UUID` varchar(64) NOT NULL,
  `BUILD_ID` varchar(64) NOT NULL,
  PATROL_EMPLOYEE_ID varchar(64) DEFAULT NULL,
  PATROL_EMPLOYEE_NAME varchar(512) DEFAULT NULL,
  PATROL_GROUP_ID varchar(64) DEFAULT NULL,
  PATROL_GROUP_NAME varchar(512) DEFAULT NULL,
  PATROL_PATH_DATA_DISPLAY_ID varchar(64) DEFAULT NULL,
  PRIMARY KEY (`UUID`),
  KEY `AREA_EMPLOYEE_REL_PATH_DATA_ID` (`PATROL_PATH_DATA_DISPLAY_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



DROP TABLE IF EXISTS PATROL_EMPLOYEE_DATA_DISPLAY;
-- 巡检人员展示数据表 PATROL_EMPLOYEE_DATA_DISPLAY类
CREATE TABLE `PATROL_EMPLOYEE_DATA_DISPLAY` (
  `UUID` varchar(64) NOT NULL,
  `BUILD_ID` varchar(64) NOT NULL,
  PATROL_EMPLOYEE_ID varchar(64) DEFAULT NULL,
  PATROL_EMPLOYEE_NAME varchar(512) DEFAULT NULL,
  PATROL_GROUP_ID varchar(64) DEFAULT NULL,
  DATE_TYPE varchar(64) DEFAULT NULL,
  PATROL_GROUP_NAME varchar(512) DEFAULT NULL,
  PATROL_TIME_LENGTH INT(11) DEFAULT NULL,
  PATROL_PATH_NUM INT(11) DEFAULT NULL,
  PATROL_AREA_NUM INT(11) DEFAULT NULL,
  PATROL_AREA_TARGET_RATE varchar(64) DEFAULT NULL,
  PATROL_DATE varchar(64) DEFAULT NULL,
  CREATE_TIME datetime DEFAULT NULL,
  PRIMARY KEY (`UUID`),
  KEY `PATROL_EMPLOYEE_DATA_DISPLAY_BUILD_ID` (`BUILD_ID`),
  KEY `PATROL_EMPLOYEE_DATA_DISPLAY_DATE_TYPE` (`DATE_TYPE`),
  KEY `PATROL_EMPLOYEE_DATA_DISPLAY_PATROL_DATE` (`PATROL_DATE`),
  KEY `PATROL_EMPLOYEE_DATA_DISPLAY_PATROL_GROUP_ID` (`PATROL_GROUP_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



DROP TABLE IF EXISTS EMPLOYEE_AREA_REL_DATA_DISPLAY;
-- 巡检人员与区域展示数据关联表 EMPLOYEE_AREA_REL_DATA_DISPLAY
CREATE TABLE `EMPLOYEE_AREA_REL_DATA_DISPLAY` (
  `UUID` varchar(64) NOT NULL,
  `BUILD_ID` varchar(64) NOT NULL,
  PATROL_AREA_ID varchar(64) DEFAULT NULL,
  PATROL_AREA_NAME varchar(512) DEFAULT NULL,
  PATROL_SUCCESS_NUM INT(11) DEFAULT NULL,
  PATROL_FAIL_NUM INT(11) DEFAULT NULL,
  EMPLOYEE_DATA_DISPLAY_ID varchar(64) DEFAULT NULL,
  PRIMARY KEY (`UUID`),
  KEY `EMPLOYEE_AREA_REL_EMPLOYEE_DISPLAY_ID` (`EMPLOYEE_DATA_DISPLAY_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS EMPLOYEE_PATH_REL_DATA_DISPLAY;
-- 巡检人员与路线展示数据关联表 EMPLOYEE_PATH_REL_DATA_DISPLAY
CREATE TABLE `EMPLOYEE_PATH_REL_DATA_DISPLAY` (
  `UUID` varchar(64) NOT NULL,
  `BUILD_ID` varchar(64) NOT NULL,
  PATROL_PATH_ID varchar(64) DEFAULT NULL,
  PATROL_PATH_NAME varchar(512) DEFAULT NULL,
  PATROL_SUCCESS_NUM INT(11) DEFAULT NULL,
  PATROL_FAIL_NUM INT(11) DEFAULT NULL,
  EMPLOYEE_DATA_DISPLAY_ID varchar(64) DEFAULT NULL,
  PRIMARY KEY (`UUID`),
  KEY `EMPLOYEE_PATH_REL_EMPLOYEE_DISPLAY_ID` (`EMPLOYEE_DATA_DISPLAY_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS PATH_DAY_DATA_DISPLAY;
-- 巡检路线每天的统计数据表 PATH_DAY_DATA_DISPLAY
CREATE TABLE `PATH_DAY_DATA_DISPLAY` (
  `UUID` varchar(64) NOT NULL,
  `BUILD_ID` varchar(64) NOT NULL,
  PATROL_PATH_ID varchar(64) DEFAULT NULL,
  PATROL_PATH_NAME varchar(512) DEFAULT NULL,
  PATROL_SUCCESS_NUM INT(11) DEFAULT NULL,
  PATROL_FAIL_NUM INT(11) DEFAULT NULL,
  PATROL_GROUP_IDS varchar(4096) DEFAULT NULL,
  PATROL_AREA_IDS varchar(4096) DEFAULT NULL,
  PATROL_DATE varchar(64) DEFAULT NULL,
  PATROL_STATUS tinyint(1) DEFAULT 0,
  CREATE_TIME datetime DEFAULT NULL,
  PRIMARY KEY (`UUID`),
  KEY `PATH_DAY_DATA_DISPLAY_BUILD_ID` (`BUILD_ID`),
  KEY `PATH_DAY_DATA_DISPLAY_PATROL_PATH_ID` (`PATROL_PATH_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS AREA_DAY_DATA_DISPLAY;
-- 巡检区域每天的统计数据表 AREA_DAY_DATA_DISPLAY
CREATE TABLE `AREA_DAY_DATA_DISPLAY` (
  `UUID` varchar(64) NOT NULL,
  `BUILD_ID` varchar(64) NOT NULL,
  PATROL_AREA_ID varchar(64) DEFAULT NULL,
  PATROL_AREA_NAME varchar(512) DEFAULT NULL,
  PATROL_SUCCESS_NUM INT(11) DEFAULT NULL,
  PATROL_FAIL_NUM INT(11) DEFAULT NULL,
  PATROL_GROUP_IDS varchar(4096) DEFAULT NULL,
  PATROL_PATH_IDS varchar(4096) DEFAULT NULL,
  PATROL_DATE varchar(64) DEFAULT NULL,
  PATROL_STATUS tinyint(1) DEFAULT 0,
  CREATE_TIME datetime DEFAULT NULL,
  PRIMARY KEY (`UUID`),
  KEY `AREA_DAY_DATA_DISPLAY_BUILD_ID` (`BUILD_ID`),
  KEY `AREA_DAY_DATA_DISPLAY_PATROL_PATH_ID` (`PATROL_AREA_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;




DROP TABLE IF EXISTS GROUP_DAY_DATA_DISPLAY;
-- 巡检班组每天的统计数据表 GROUP_DAY_DATA_DISPLAY
CREATE TABLE `GROUP_DAY_DATA_DISPLAY` (
  `UUID` varchar(64) NOT NULL,
  `BUILD_ID` varchar(64) NOT NULL,
  PATROL_GROUP_ID varchar(64) DEFAULT NULL,
  PATROL_GROUP_NAME varchar(512) DEFAULT NULL,
  PATROL_PATH_SUCCESS_NUM INT(11) DEFAULT NULL,
  PATROL_PATH_FAIL_NUM INT(11) DEFAULT NULL,
  PATROL_TOTAL_TIME_LENGTH INT(11) DEFAULT NULL,
  PATROL_DATE varchar(64) DEFAULT NULL,
  CREATE_TIME datetime DEFAULT NULL,
  PRIMARY KEY (`UUID`),
  KEY `GROUP_DAY_DATA_DISPLAY_BUILD_ID` (`BUILD_ID`),
  KEY `GROUP_DAY_DATA_DISPLAY_PATROL_PATH_ID` (`PATROL_GROUP_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

drop table if exists SYS_LOGO;
create table SYS_LOGO(
`UUID` varchar(36) NOT NULL DEFAULT '',
`THEME` varchar(256) DEFAULT NULL,
`NAME` varchar(256) DEFAULT NULL,
PRIMARY KEY (`UUID`)
);

DROP table  IF EXISTS `ROPE_ALARM`;
create table `ROPE_ALARM` (
UUID varchar(32) default '',
SN varchar(32) not null,
ADDR varchar(256) not null,
REMARK text,
X int,
Y int,
BUILD_ID varchar(12) not null,
FLOOR_NO varchar(12) not null,
BATTERY int default '-1',
IN_ALARM tinyint(1) default '0',
STATUS tinyint(1) default '0',
CREATE_BY varchar(128),
CREATE_TIME datetime,
UPDATE_BY varchar(128),
UPDATE_TIME datetime,
primary key(`UUID`),
KEY `IDX_ROPE_ALARM_SN` (`SN`),
KEY `IDX_ROPE_ALARM_BUILD_ID` (`BUILD_ID`),
KEY `IDX_ROPE_ALARM_FLOOR_NO` (`FLOOR_NO`),
KEY `IDX_ROPE_ALARM_ADDR` (`ADDR`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;














